
from __future__ import annotations


# node labels
CLAIM = "Claim"
BROKER = "Broker"
CEDANT = "Cedant"
INSURED = "Insured"
USER = "User"
PROCESS_INSTANCE = "ProcessInstance"
PAYMENT = "Payment"
LOCATION = "Location"
QUERY = "Query"

STRUCTURED_NODE_LABELS = [
    CLAIM, BROKER, CEDANT, INSURED, USER,
    PROCESS_INSTANCE, PAYMENT, LOCATION, QUERY,
]


NOTE = "Note"


# Relationship types

SUBMITTED = "SUBMITTED"
HAS_CLAIM = "HAS_CLAIM"
HAS_PROCESS = "HAS_PROCESS"
INITIATED = "INITIATED"
CREATED = "CREATED"
MODIFIED = "MODIFIED"
APPROVED = "APPROVED"
HAS_PAYMENT = "HAS_PAYMENT"
HAS_QUERY = "HAS_QUERY"
OCCURRED_IN = "OCCURRED_IN"
HAS_NOTE = "HAS_NOTE"

RELATIONSHIP_TYPES = [
    SUBMITTED, HAS_CLAIM, HAS_PROCESS, INITIATED, CREATED,
    MODIFIED, APPROVED, HAS_PAYMENT, HAS_QUERY, OCCURRED_IN, HAS_NOTE,
]

# (source label, relationship, target label)
PATTERNS = [
    (BROKER, SUBMITTED, CLAIM),
    (CEDANT, HAS_CLAIM, CLAIM),
    (INSURED, HAS_CLAIM, CLAIM),
    (USER, INITIATED, CLAIM),
    (USER, CREATED, CLAIM),
    (USER, MODIFIED, CLAIM),
    (USER, APPROVED, CLAIM),
    (CLAIM, HAS_PROCESS, PROCESS_INSTANCE),
    (CLAIM, HAS_PAYMENT, PAYMENT),
    (CLAIM, HAS_QUERY, QUERY),
    (CLAIM, OCCURRED_IN, LOCATION),
    (CLAIM, HAS_NOTE, NOTE),
]

GRAPHRAG_ALLOWED_RELATIONSHIPS = RELATIONSHIP_TYPES

# Node labels eligible for vector search / embedding.
EMBEDDABLE_LABELS = [NOTE]

VECTOR_INDEX_NAME = "knowledge_embedding_index"

CLIENT_DOMAINS_PROPERTY = "client_domains"
